#!/usr/bin/env ruby

# frozen_string_literal: true

require 'bundler/setup'

require 'optparse'

require_relative 'lib/ynai/config'
require_relative 'lib/ynai/configurator'
require_relative 'lib/ynai/database'
require_relative 'lib/ynai/push'
require_relative 'lib/ynai/ynab'

refresh_accounts = false
update_mapping = false

OptionParser.new do |opts|
  opts.banner = 'Usage: push [options]'

  opts.separator ''
  opts.separator 'Common options:'

  opts.on('-r', '--refresh-accounts', 'Refresh YNAB accounts') do
    refresh_accounts = true
  end

  opts.on('-m', '--update-mapping', 'Update account mapping') do
    update_mapping = true
  end

  opts.on_tail('-h', '--help', 'Show this message') do
    puts opts
    exit
  end
end.parse!

db = Ynai::Database.get

configurator = Ynai::Configurator.new()
configurator.db = db

config = Ynai::Config.new(db, configurator)
configurator.config = config

ynab = Ynai::YNAB.new(config)
configurator.ynab = ynab

command = Ynai::Push.new(config, db, ynab)

config.delete 'push.accounts' if refresh_accounts
config.delete 'push.mapping' if update_mapping

command.run()
