#!/usr/bin/env ruby

# frozen_string_literal: true

require 'bundler/setup'

require 'optparse'

require_relative 'lib/config'
require_relative 'lib/database'
require_relative 'lib/push'

refresh_accounts = false
update_mapping = false

OptionParser.new do |opts|
  opts.banner = 'Usage: push [options]'

  opts.separator ''
  opts.separator 'Common options:'

  opts.on('-r', '--refresh-accounts', 'Refresh YNAB accounts') do
    refresh_accounts = true
  end

  opts.on('-m', '--update-mapping', 'Update account mapping') do
    update_mapping = true
  end

  opts.on_tail('-h', '--help', 'Show this message') do
    puts opts
    exit
  end
end.parse!

db = Ynai::Database.get

config = Ynai::Config.new(db)

command = Ynai::Push.new(config, db)

command.run(refresh_accounts, update_mapping)
